--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/4/2021 10:30:11 PM
-- Server version: 5.5.5-10.1.47-MariaDB-0ubuntu0.18.04.1
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO public.employee(employee_id, employee_code, employee_name, dob, address, phone_number, email, gender, identify_number, shift, pass_word, status, join_date, group_id) VALUES
('12437806-26ac-3517-9c0b-87ae14180c33', 'EM593', 'Trần Thị Thọ', '1985-02-09', '1146 Rose Hill Avenue', '(323) 129-1050', 'AbigailKruse91@nowhere.com', 2, '2858173260', 1, 'DWV3F6', 1, '2018-01-14', '699acaa2-66da-563a-1702-ce5da15ac776'),
('148ed882-32b8-218e-9c20-39c2f00615e8', 'EM246', 'Vũ Thị Kiên', '1968-04-30', '1821 Mountain Ct', '(298) 926-2969', 'Ligon@example.com', 1, '7949370504', 2, '15KP0G', 0, '2021-05-10', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('14ee7bc0-194c-3948-57be-406293204378', 'EM268', 'Trần Văn Công', '1968-10-15', '1698 White Hunting Hill Ct', '(883) 613-5067', 'Julene.IAbrams@example.com', 2, '2339290570', 3, '5QYN47', 0, '2019-08-15', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('15cb3909-1246-2add-33de-23e177779933', 'EM348', 'Nông Đức Ánh', '1952-10-08', '53 Quailwood Loop', '(175) 057-8554', 'Kimberlee_ZCausey@nowhere.com', 2, '7352442211', 3, '58M048', 1, '2018-01-09', '699acaa2-66da-563a-1702-ce5da15ac776'),
('15d0d796-1465-4665-fc83-196123975cb2', 'EM789', 'Đinh Văn Hạnh', '1984-01-24', '3796 1st Ct', '(190) 627-1641', 'SeeWild56@example.com', 1, '5343008296', 1, 'I39FR3', 0, '2019-04-23', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('182ac03d-3bc5-1d27-7309-bf1378b8dc91', 'EM101', 'Hoàng Kim Nguyên', '1951-01-05', '663 Glenwood Dr', '(877) 128-5657', 'wxdo5147@example.com', 0, '0125127120', 1, 'AT99Y5', 0, '2021-04-02', '699acaa2-66da-563a-1702-ce5da15ac776'),
('1b691e79-236d-5b5a-9d20-39c2f00615e8', 'EM422', 'Trần Ngọc Vinh', '1976-05-21', '486 Highland Dr', '(531) 501-8295', 'Cedric.CSotelo@example.com', 2, '3204925887', 2, '49ECKY', 1, '2019-03-04', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('1d3986c3-11ae-3e82-85c0-08fd2f807219', 'EM469', 'Hoàng Anh Đan', '1971-07-20', '428 SW Town Highway', '(890) 191-4526', 'Jude_Weller976@example.com', 2, '8531367933', 3, 'MFF3B0', 1, '2019-02-07', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('1f94a596-32c4-2a29-8ad5-ba100c6f7bce', 'EM465', 'Trần Việt Thảo', '1963-06-23', '3008 W Hunting Hill Street', '(791) 539-4168', 'MarcoBerry@example.com', 2, '1643324242', 2, '92M309', 1, '2018-08-21', '699acaa2-66da-563a-1702-ce5da15ac776'),
('204c0070-4a99-51b1-7209-bf1378b8dc91', 'EM038', 'Nông Thị Chi', '1977-11-26', '16 Mountain St', '(434) 643-2196', 'SmithO@example.com', 1, '7104052912', 1, '278MGD', 1, '2019-05-27', '699acaa2-66da-563a-1702-ce5da15ac776'),
('20bbbd0b-3c4a-7d94-6f09-bf1378b8dc91', 'EM671', 'Nguyễn Vân Lệ', '1961-10-24', '31 SW Riverview Hwy', '(726) 780-7028', 'CatherynTaber@example.com', 2, '6311969326', 1, '216Z88', 0, '2018-01-31', '699acaa2-66da-563a-1702-ce5da15ac776'),
('22f29725-54f0-11f0-9d0b-87ae14180c33', 'EM929', 'Vũ Vân Trà', '1959-07-13', '521 SW Flintwood Pkwy', '(709) 214-4070', 'DorothaCass344@example.com', 2, '2397234919', 1, 'P1Z62T', 1, '2018-12-04', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('234d2569-6b1c-720c-9f20-39c2f00615e8', 'EM156', 'Trần Thị Mỹ', '1973-05-20', '85 N Ironwood Hwy', '(596) 640-1634', 'Whitaker@nowhere.com', 1, '5986026193', 3, 'Q729G4', 1, '2018-03-22', '699acaa2-66da-563a-1702-ce5da15ac776'),
('2520d168-1494-4217-89d5-ba100c6f7bce', 'EM796', 'Nguyễn Vân Bích', '1993-07-25', '3948 East Parkwood Lane', '(685) 825-8109', 'YasmineJensen@example.com', 0, '3400280652', 3, '97Z421', 0, '2019-12-26', '699acaa2-66da-563a-1702-ce5da15ac776'),
('2535c718-4dd9-311b-8cd5-ba100c6f7bce', 'EM314', 'Nguyễn Tú Thúy', '1951-09-01', '3490 S Riverside Street', '(615) 958-2687', 'Aguiar7@nowhere.com', 1, '9656123679', 1, 'E2MD31', 0, '2019-12-10', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('25502e11-38ba-4c53-fe83-196123975cb2', 'EM120', 'Trần Thị Chi', '1955-10-03', '2472 White Pine Tree Way', '(642) 688-5246', 'Washburn156@example.com', 0, '1436902788', 2, 'GZI83U', 0, '2020-12-04', '699acaa2-66da-563a-1702-ce5da15ac776'),
('25c6c36e-1668-7d10-6e09-bf1378b8dc91', 'EM768', 'Trần Diễm Đăng', NULL, NULL, '(326) 891-3864', NULL, NULL, '3980583308', 1, 'UIIBV5', 1, '2018-08-23', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('26de5798-48e1-14d3-9f0b-87ae14180c33', 'EM518', 'Nguyễn Thị Thọ', NULL, NULL, '(904) 187-6158', NULL, NULL, '1565635715', 2, NULL, 0, '2018-08-30', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('28018b36-16ff-393b-a020-39c2f00615e8', 'EM705', 'Trịnh Văn Thảo', '1959-10-27', '251 SW Woodrow Highway', '(831) 860-1449', 'hqjoe3@example.com', 2, '8036078926', 1, 'O6S6BC', 1, '2020-08-13', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('2cc5723c-56c3-7df9-8bd5-ba100c6f7bce', 'EM129', 'Vũ Khánh Giang', '1959-07-18', '371 Brentwood Parkway', '(512) 822-2246', 'oxfz2718@nowhere.com', 0, '3518042072', 2, '38B38I', 1, '2018-10-01', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('2ea8deee-1b95-2a51-88d5-ba100c6f7bce', 'EM836', 'Nguyễn Thị Bằng', '1951-01-31', '3937 Hunting Hill Avenue', '(248) 158-1877', 'Verline_Fairbanks2@example.com', 0, '9803416134', 3, NULL, 1, '2019-12-18', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('354f1b13-17bf-1b52-87d5-ba100c6f7bce', 'EM938', 'Trần Ánh Hồng', '1994-07-20', '581 SW Fox Hill Cir', '(389) 664-8463', 'GeorgannSamples457@example.com', 1, '7553058469', 3, NULL, 1, '2018-07-02', '699acaa2-66da-563a-1702-ce5da15ac776'),
('357d7c4e-4b7f-11c2-84c0-08fd2f807219', 'EM745', 'Trần Thị Tùng', '1968-09-27', '501 Old Rose Hill Hwy', '(648) 376-0672', 'Luther@example.com', 0, '1197839854', 2, NULL, 1, '2018-01-06', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('36104b10-705b-57a8-83c0-08fd2f807219', 'EM144', 'Mai Vân Nhật', '1953-07-03', '941 Market Dr', '(312) 593-2034', 'Abreu222@example.com', 2, '4883365049', 2, '2T33J6', 0, '2019-05-21', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('3700cc49-55b5-69ea-4929-a2925c0f334d', 'EM839', 'Hồ Văn Liên', '1962-07-18', '101 Meadowview Pkwy', '(905) 230-0670', 'Burrows865@example.com', 0, '0006044110', 2, '3RDXF5', 0, '2018-10-26', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('37dd9bb0-4c53-4134-31de-23e177779933', 'EM493', 'Hoàng Trọng Liên', '1952-07-20', '145 SW Deepwood Hwy', '(129) 310-7243', 'ssmxzviy.qout@example.com', 2, '8914143635', 3, '61P2U0', 1, '2020-07-03', '699acaa2-66da-563a-1702-ce5da15ac776'),
('38528581-656f-2902-32de-23e177779933', 'EM967', 'Đinh Tiến Hà', NULL, NULL, '(284) 669-3516', NULL, NULL, '4273560783', 1, '1SW95W', 1, '2018-05-29', '699acaa2-66da-563a-1702-ce5da15ac776'),
('38fae0a4-2a8d-7751-17cf-9712082ff6cb', 'EM192', 'Đinh Thị Chương', '1951-02-27', '235 Brentwood St', '(339) 239-5458', 'Domingo_V.Gresham@example.com', 2, '3705667228', 2, '49EAYR', 0, '2021-03-30', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('3b86d2ed-446c-5fce-56be-406293204378', 'EM774', 'Hồ Quốc Vinh', '1996-03-23', '2876 West Ashwood Ln', '(946) 885-9296', 'Loftis@example.com', 1, '8832477294', 3, '8X459W', 0, '2019-06-27', '699acaa2-66da-563a-1702-ce5da15ac776'),
('3bad7541-7915-6d1b-34de-23e177779933', 'EM379', 'Võ Anh Lệ', '1959-10-23', '913 East Woodrow Way', '(266) 681-8929', 'Bernard_Jeffers167@example.com', 0, '1145602053', 3, NULL, 0, '2019-06-07', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('40480f96-2014-7c36-4c29-a2925c0f334d', 'EM223', 'Mai Mỹ Thanh', '1966-07-07', '194 Red Mount Pkwy', '(464) 427-2112', 'HazelW@example.com', 2, '8922668357', 1, 'FWUN39', 1, '2018-01-03', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('40dcb887-554e-6059-a120-39c2f00615e8', 'EM976', 'Vũ Hưng Phi', '1968-04-28', '1155 Beachwood Court', '(159) 534-8146', 'SalleyBeckett@example.com', 1, '6367459132', 1, 'A9R9N5', 1, '2018-11-02', '699acaa2-66da-563a-1702-ce5da15ac776'),
('41c2dce0-2c38-3bc6-16cf-9712082ff6cb', 'EM667', 'Nguyễn Văn Nghị', '1968-09-08', '135 Edgewood Rd', '(117) 729-0477', 'ErrolAlcala24@example.com', 0, '8533743953', 1, 'K3ZJN3', 1, '2018-08-20', '699acaa2-66da-563a-1702-ce5da15ac776'),
('486f3705-5928-5b0d-15cf-9712082ff6cb', 'EM146', 'Nguyễn Thị Chính', '1960-05-29', '3746 South Rose Hill Dr', '(559) 287-6791', 'SolomonBarela3@example.com', 2, '8612688588', 3, 'Y8168I', 1, '2018-01-01', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('4931f441-237d-4e19-9e0b-87ae14180c33', 'EM516', 'Võ Văn Nga', '1952-09-14', '2358 Fox Hill Ln', '(173) 393-4530', 'Abdul_Foy@nowhere.com', 0, '4931764561', 1, 'L73V5S', 0, '2021-03-15', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('4a4a8c90-2e57-215e-58be-406293204378', 'EM290', 'Vũ Ánh Hoài', NULL, NULL, '(547) 074-8716', NULL, NULL, '8404488166', 2, 'CSTO0K', 1, '2019-04-29', '699acaa2-66da-563a-1702-ce5da15ac776'),
('4d759fc8-400f-6e8f-5bbe-406293204378', 'EM578', 'Nguyễn Văn Bằng', '1951-04-08', '2724 New Glenwood Dr', '(682) 404-3526', 'Phillips9@example.com', 2, '1931431940', 3, '4UV9AP', 1, '2020-07-10', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('4fbf7ac2-4f95-259e-fd83-196123975cb2', 'EM740', 'Nguyễn Trọng Điệp', '1985-10-15', '100 Flintwood Ct', '(889) 518-4429', 'Adela_Scarborough@example.com', 1, '6474269748', 2, '830OQ8', 1, '2018-01-11', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('53baae5e-52f2-2642-4a29-a2925c0f334d', 'EM365', 'Nguyễn Văn Liên', '1969-11-07', '3091 Fox Hill Way', '(892) 490-6962', 'Severson757@example.com', 0, '6697529949', 3, '316OMC', 1, '2018-07-23', '699acaa2-66da-563a-1702-ce5da15ac776'),
('57a3f48f-1c1d-1f04-9e20-39c2f00615e8', 'EM184', 'Hoàng Văn Lương', '1951-01-14', '2935 Cedar Tree Highway', '(684) 862-0403', 'jnmo3690@nowhere.com', 0, '2849671275', 1, 'NU7YSU', 0, '2020-09-12', '699acaa2-66da-563a-1702-ce5da15ac776'),
('5c9f5f1a-6f5c-49cc-59be-406293204378', 'EM990', 'Nguyễn Linh Giang', '1989-10-20', '27 Buttonwood Pkwy', '(906) 068-8306', 'zqmfvtd2720@example.com', 2, '4207801487', 3, 'FD3NSS', 1, '2018-11-27', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('5ee2ba7f-49ee-5b09-5cbe-406293204378', 'EM535', 'Nguyễn Anh Anh', NULL, NULL, '(402) 533-4967', NULL, NULL, '8306272252', 3, 'VA0UR3', 0, '2018-12-05', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('62a849b4-1145-4227-7009-bf1378b8dc91', 'EM936', 'Trịnh Thành Ánh', '1962-03-16', '1207 W Social Ct', '(843) 443-5571', 'Sikes@example.com', 0, '1787297076', 3, 'GWC4VB', 0, '2020-08-26', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('6b47b37f-3123-3ce7-14cf-9712082ff6cb', 'EM175', 'Nguyễn Việt Đăng', '1992-12-16', '54 West Quailwood Avenue', '(103) 512-5221', 'Francene.E.Acker869@example.com', 2, '5495058048', 3, 'J56A83', 1, '2019-07-21', '699acaa2-66da-563a-1702-ce5da15ac776'),
('6c2d254c-51c8-2ac9-7409-bf1378b8dc91', 'EM442', 'Nguyễn Văn Hiền', '1951-02-23', '582 New Edgewood Rd', '(155) 159-0140', 'AdolphAcker49@example.com', 0, '5223389138', 1, 'Q59954', 0, '2019-06-22', '699acaa2-66da-563a-1702-ce5da15ac776'),
('6e98d16d-1cee-3d90-4d29-a2925c0f334d', 'EM419', 'Vũ Ngọc Nghị', '1959-06-15', '1695 Waterview Avenue', '(723) 868-2413', 'Jarvis_Nugent157@example.com', 1, '8967279144', 2, '897YR8', 1, '2019-12-25', '699acaa2-66da-563a-1702-ce5da15ac776'),
('749af78e-699e-5d1e-7109-bf1378b8dc91', 'EM652', 'Nguyễn Văn Bình', '1960-05-26', '690 East Riverview St', '(224) 768-0727', 'Sims4@example.com', 2, '9098329888', 3, 'LN4AD3', 0, '2018-04-07', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde'),
('749f165c-16de-4b32-86c0-08fd2f807219', 'EM704', 'Trần Thị Giang', '1952-01-18', '989 Quailwood Ct', '(106) 109-6937', 'Krebs769@example.com', 1, '6728691543', 2, '128Z8Z', 1, '2018-12-22', '699acaa2-66da-563a-1702-ce5da15ac776'),
('7c94355d-4702-3a9b-5abe-406293204378', 'EM117', 'Trần Trí Hương', '1958-11-20', '681 Mount Lane', '(229) 509-0022', 'GennieGBarrow9@example.com', 0, '8358160750', 1, 'Z0S3GJ', 0, '2018-04-11', '699acaa2-66da-563a-1702-ce5da15ac776'),
('7dbd90f6-6015-12c6-4b29-a2925c0f334d', 'EM830', 'Trịnh Thị Quân', '1951-01-06', '3062 Hunting Hill Pkwy', '(286) 642-2495', 'Burch@example.com', 1, '3907680818', 3, '18ZUW8', 1, '2019-11-29', '2f1172a9-1b5d-6fc4-777e-3e3b283cabde');