--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/4/2021 10:30:58 PM
-- Server version: 5.5.5-10.1.47-MariaDB-0ubuntu0.18.04.1
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO public."group"(group_id, group_name, base_salary) VALUES
('2f1172a9-1b5d-6fc4-777e-3e3b283cabde', 'employeee', 10000000),
('699acaa2-66da-563a-1702-ce5da15ac776', 'maneger', 5000000);